/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontBoaLeitura;

import br.ufmt.ic.alg3.ap2.dao.impl.ClienteDaoImpl;
import javax.swing.JOptionPane;

/**
 *
 * @author enzob
 */
public class CadastroCliente extends javax.swing.JFrame {
    

    /**
     * Creates new form CadastroLivro
     */
    public CadastroCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitle = new javax.swing.JLabel();
        labelCliente = new javax.swing.JLabel();
        textNome = new javax.swing.JTextField();
        labelCPF = new javax.swing.JLabel();
        textCPF = new javax.swing.JTextField();
        labelEndereco = new javax.swing.JLabel();
        textEndereco = new javax.swing.JTextField();
        ConfirmBTN = new javax.swing.JButton();
        labelTelefone = new javax.swing.JLabel();
        textTelefone = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(440, 440));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitle.setText("Cadastro Cliente");
        getContentPane().add(labelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 130, 60));

        labelCliente.setText("Nome:");
        getContentPane().add(labelCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 90, 40));

        textNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNomeActionPerformed(evt);
            }
        });
        textNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textNomeKeyTyped(evt);
            }
        });
        getContentPane().add(textNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 240, 30));

        labelCPF.setText("CPF:");
        getContentPane().add(labelCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 90, 40));

        textCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textCPFKeyTyped(evt);
            }
        });
        getContentPane().add(textCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 240, 30));

        labelEndereco.setText("Endereço:");
        getContentPane().add(labelEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 70, 30));

        textEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEnderecoActionPerformed(evt);
            }
        });
        getContentPane().add(textEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 240, 30));

        ConfirmBTN.setText("Adicionar");
        ConfirmBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmBTNActionPerformed(evt);
            }
        });
        getContentPane().add(ConfirmBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 140, 40));

        labelTelefone.setText("Telefone:");
        getContentPane().add(labelTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 70, 30));

        textTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTelefoneActionPerformed(evt);
            }
        });
        textTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textTelefoneKeyTyped(evt);
            }
        });
        getContentPane().add(textTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 240, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNomeActionPerformed

    private void ConfirmBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmBTNActionPerformed
    ClienteDaoImpl saveClient = new ClienteDaoImpl();
    saveClient.salvar(textCPF.getText(), textNome.getText(), textEndereco.getText(), textTelefone.getText());
    JOptionPane.showMessageDialog(null, "Cliente Cadastrado com Sucesso!");
    CadastroCliente.this.dispose();
    
    }//GEN-LAST:event_ConfirmBTNActionPerformed

    private void textEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEnderecoActionPerformed

    private void textTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTelefoneActionPerformed

    private void textTelefoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textTelefoneKeyTyped
        char c = evt.getKeyChar();
        
        if(!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_textTelefoneKeyTyped

    private void textCPFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textCPFKeyTyped
        char c = evt.getKeyChar();
        
        if(!Character.isDigit(c)) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_textCPFKeyTyped

    private void textNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textNomeKeyTyped
        char c = evt.getKeyChar();
        
        if(Character.isDigit(c)) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_textNomeKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConfirmBTN;
    private javax.swing.JLabel labelCPF;
    private javax.swing.JLabel labelCliente;
    private javax.swing.JLabel labelEndereco;
    private javax.swing.JLabel labelTelefone;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JTextField textCPF;
    private javax.swing.JTextField textEndereco;
    private javax.swing.JTextField textNome;
    private javax.swing.JTextField textTelefone;
    // End of variables declaration//GEN-END:variables
}
