/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontBoaLeitura;

import br.ufmt.ic.alg3.ap2.dao.impl.LivroDaoImpl;
import entityClasses.ClasseLivro;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author enzob
 */
public class CadastroLivroForm extends javax.swing.JFrame {

    /**
     * Creates new form CadastroClienteForm
     */
    public CadastroLivroForm() {
        initComponents();
        atualizarTabela();
    }
    private void atualizarTabela() {
           LivroDaoImpl update = new LivroDaoImpl();
           List<ClasseLivro> livros = update.Verificar();
           DefaultTableModel model = (DefaultTableModel) listaLivro.getModel();
           model.setRowCount(0); // Limpa a tabela antes de atualizá-la

           for (ClasseLivro livro : livros) {
               Object[] rowData = {
                   livro.getId(),
                   livro.getTitle(),
                   livro.getAutor(),
                   livro.getEditora(),
                   livro.getPreco()
               };
               model.addRow(rowData); // Adiciona uma nova linha à tabela
           }
       }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadastroBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaLivro = new javax.swing.JTable();
        deleteBTN = new javax.swing.JButton();
        AtualizarBTN = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cadastroBTN.setText("Cadastrar");
        cadastroBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroBTNActionPerformed(evt);
            }
        });
        getContentPane().add(cadastroBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 90, 40));

        listaLivro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Título", "Autor", "Editora", "Preço"
            }
        ));
        jScrollPane1.setViewportView(listaLivro);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 500, 410));

        deleteBTN.setText("Remover");
        deleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTNActionPerformed(evt);
            }
        });
        getContentPane().add(deleteBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 90, 40));

        AtualizarBTN.setText("Atualizar");
        AtualizarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizarBTNActionPerformed(evt);
            }
        });
        getContentPane().add(AtualizarBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 90, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastroBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroBTNActionPerformed
        CadastroLivro newLivro = new CadastroLivro();
        newLivro.setVisible(true);
    }//GEN-LAST:event_cadastroBTNActionPerformed

    private void deleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTNActionPerformed
        int selectedRow = listaLivro.getSelectedRow();
        if (selectedRow != -1) {
            // Exiba uma caixa de diálogo de confirmação
            int resposta = JOptionPane.showConfirmDialog(null, "Deseja excluir o Livro selecionado?", "Confirmação de Exclusão", JOptionPane.YES_NO_OPTION);

            if (resposta == JOptionPane.YES_OPTION) {
                DefaultTableModel model = (DefaultTableModel) listaLivro.getModel();
                int idLivroExcluir = (int) model.getValueAt(selectedRow, 0);

                LivroDaoImpl deleteDB = new LivroDaoImpl();
                boolean exclusaoBemSucedida = deleteDB.deletar(idLivroExcluir);

                if (exclusaoBemSucedida) {
                    // Remova a linha da tabela se a exclusão no banco de dados for bem-sucedida
                    model.removeRow(selectedRow);
                } else {
                    // Lidere com a exclusão mal-sucedida, se necessário
                    JOptionPane.showMessageDialog(null, "Exclusão mal-sucedida.", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            // Exiba uma mensagem ao usuário informando que nenhuma linha foi selecionada.
            JOptionPane.showMessageDialog(null, "Nenhuma linha selecionada.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_deleteBTNActionPerformed

    private void AtualizarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarBTNActionPerformed
        atualizarTabela();
    }//GEN-LAST:event_AtualizarBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroLivroForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroLivroForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroLivroForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroLivroForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroLivroForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AtualizarBTN;
    private javax.swing.JButton cadastroBTN;
    private javax.swing.JButton deleteBTN;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listaLivro;
    // End of variables declaration//GEN-END:variables
}
